# Generated by Django 5.2.4 on 2025-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_reply_comment_alter_reply_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='فایل صوتی'),
        ),
    ]
